### ISSUE TITLE
Not able to Sign-In/register

### ISSUE THREAD

**Issue by gallagts** [samcaulfield/pml-studio#12] opened 2016-03-13 13:00 UTC
Similar to when the lecturer tried to log in and register, I am given the message "registration/log-in failed". I am able to sign in using 3rd Party. However, files are not being saved to the server once signed in (Or the program is not able to find it once saved).

I tried cleaning, then removing everything and starting from scratch, but the error persists.

Edit: I am not sure if this is also because of the sign in or not, but PML check is not working.Because of this, I think that it may be a problem connecting to the server, as all problems seem to be connected to the server in some way.

**Comment by samcaulfield** [comment] 2016-03-13 13:12
I've run a clean installation and cannot reproduce this behaviour with the given information.

Please provide the following information:

1. Exact steps to reproduce the problem.
2. Are the dependencies installed?
3. What version of the project are you using? (commit SHA is more useful that version number)
4. Details of the system the project is running on.

**Comment by gallagts** [comment] 2016-03-13 13:18
Steps:
- git pull
- cd pml-studio
- make install-deps (no problems)
- make install ProjectName=raid
- make smoke-test ProjectName=raid (said all was good)
- Opened localhost
- Entered troyg93@live.ie (An old email I used to use). 
- Error: Registration Failed!

**Comment by samcaulfield** [comment] 2016-03-13 13:30
I can't reproduce this behaviour given the above information.

I'm assuming you're logging in via `Account (Not signed in) > Sign in`. Is this correct?

What password are you entering? If the password is sensitive, please find another that preserves the same behaviour and share it please.

What system is the project running on?

**Comment by gallagts** [comment] 2016-03-13 13:33
Yes, I wasn't aware of any other log in method.

Password: foobar
System: fierfox on linux emulator

**Comment by seanlth** [comment] 2016-03-13 13:34
Cant login eider

**Comment by samcaulfield** [comment] 2016-03-13 13:46
Now that I know you're running on a virtual machine I tried to produce this behaviour on a virtual machine of my own. However, I can't reproduce this behaviour.

Can you post new comments instead of adding significant information via edits as I don't get notified for edits. Cheers.

Please post the output of this command `ls -l /var/www/html/raid`

**Comment by gallagts** [comment] 2016-03-13 13:47
I will do in future.

The result is this:
total 8
-rw-r--r-- 1 www-data root 7585 Mar 13 12:55 index.html
drwxr-xr-x 2 www-data root   60 Mar 13 12:55 js
drwxr-xr-x 2 www-data root  160 Mar 13 12:55 php
drwxr-xr-x 4 www-data root   80 Mar 13 12:55 thirdparty
drwxr-xr-x 2 www-data root   40 Mar 13 12:55 userdata
-rw-r--r-- 1 www-data root    0 Mar 13 12:55 user.db

**Comment by samcaulfield** [comment] 2016-03-13 13:59
Can you delete the repository directory on your machine, clone it again and then run this command in the repository directory.

`make install-deps > output.log`

Then attach the log file to this issue.

**Comment by gallagts** [comment] 2016-03-13 14:38
Result:
make install-deps > output.log
Cloning into 'peos'...
remote: Counting objects: 9662, done.
remote: Total 9662 (delta 0), reused 0 (delta 0), pack-reused 9662
Receiving objects: 100% (9662/9662), 11.03 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (4905/4905), done.
Checking connectivity... done.
E: Unable to correct problems, you have held broken packages.
make[2]: yacc: Command not found
make[2]: *** [parser.c] Error 127
make[1]: *** [all] Error 2

**Comment by gallagts** [comment] 2016-03-13 14:39
Whoops, missed the log,and it seems, I missed the errors the forst time I did it.

**Comment by Gulnur1** [comment] 2016-03-13 14:40
Registration and sign in works for me. Did you try another email address?

**Comment by gallagts** [comment] 2016-03-13 14:41
Won't let me upload log: Here is what it says:

if [ ! -x pmlcheck ]; then \
                git clone https://github.com/jnoll/peos.git; \
                sudo apt-get install tcl tcl-dev check expect libxml2 bison \
                flex libreadline6-dev libncurses-dev; \
                if [ -d peos ]; then \
                        cd peos/pml/ && make && cp check/pmlcheck \
                        ../../thirdparty/pmlcheck/pmlcheck; \
                fi \
        fi; \
        sudo apt-get install apache2 php5 php5-sqlite
Reading package lists...
Building dependency tree...
Reading state information...
tcl is already the newest version.
tcl set to manually installed.
libxml2 is already the newest version.
libxml2 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tcl-dev : Depends: tcl8.6-dev (>= 8.6.0-2) but it is not going to be installed
make[1]: Entering directory `/home/ubuntu/Documents/pml-studio/peos/pml'
set -e; for i in pml expr check graph; do make -C $i; done
make[2]: Entering directory `/home/ubuntu/Documents/pml-studio/peos/pml/pml'
yacc -d parser.y
make[2]: Leaving directory `/home/ubuntu/Documents/pml-studio/peos/pml/pml'
make[1]: Leaving directory `/home/ubuntu/Documents/pml-studio/peos/pml'
Reading package lists...
Building dependency tree...
Reading state information...
apache2 is already the newest version.
php5 is already the newest version.
php5-sqlite is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by gallagts** [comment] 2016-03-13 14:41
Yes, I did try another address and password.

**Comment by samcaulfield** [comment] 2016-03-13 14:43
Please post the output of the following command: `uname -a`

**Comment by gallagts** [comment] 2016-03-13 14:44
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samcaulfield** [comment] 2016-03-13 15:06
Can you try and update your packages.

`sudo apt-get update`

`sudo apt-get dist-upgrade`

Then delete and reclone the repo, and post the full output of

`make install-deps`

**Comment by gallagts** [comment] 2016-03-13 15:07
But is our project not meant to work on this version and above?

**Comment by samcaulfield** [comment] 2016-03-13 15:13
I'm only asking you to upgrade your packages, not your version of Ubuntu.

**Comment by samcaulfield** [comment] 2016-03-13 15:42
If this is the same issue Andrew had, it's very important we fix this now. When's the last time you had the project running correctly? Can you try and find the latest version that works correctly for you.

Run `git checkout commitSHA` to revert to a particular version.

**Comment by gallagts** [comment] 2016-03-13 15:44
Still updating. Think it was running fine before you updated to the makefile, but ot 100%.

**Comment by gallagts** [comment] 2016-03-13 15:44
Shite, just finished..... "Not enough space on device"......

**Comment by gallagts** [comment] 2016-03-13 15:46
I'll try something again this evening, I have to leave in a bit for  Mothers Bday Dinner

**Comment by samcaulfield** [comment] 2016-03-13 15:46
The build system was changed to makefile last night, so if you had it running between Wednesday and last night that's a really important point. Did you have it running since Wednesday?

**Comment by gallagts** [comment] 2016-03-13 15:48
Oh, was it that sson, thought you'd added it before. I think I had it
runnig for last Wednesday.

**Comment by gallagts** [comment] 2016-03-13 15:57
Actually, Ignore my past post. I never tried to sign in or use pml
check, so I have idea when it last worked.

They weren't the things I worked on.

**Comment by samcaulfield** [comment] 2016-03-13 17:00
I find it extremely likely that this is the same issue Andrew had.

We all agreed on Wednesday that everyone's job this week is for testing the project. If your system is eligible to suffer from the problem, that makes me really curious why you didn't discover it in your testing earlier in the week, since we know the problem has existed since at least Wednesday.

Gulnur has asked Eamon and Sharon to test these features. Hopefully someone else will be able to reproduce this so we'll have someone online to try and fix it.

**Comment by Gulnur1** [comment] 2016-03-13 17:20
I wonder if it is a browser issue. Can we try different browsers than Firefox? troy, which one were you using?

**Comment by sharonluk** [comment] 2016-03-13 17:32
Firefox and Chrome would be the most popular browsers used in linux. So far Registration works for me using firefox on ubuntu linux.

**Comment by samcaulfield** [comment] 2016-03-13 17:41
I hadn't thought of the browser being an issue, but I can't reproduce this on chrome or firefox.

**Comment by EamonMc** [comment] 2016-03-13 17:42
Everything is running well for me on a fresh install of Ubuntu

Only thing is the heading of the dialogue box in firefox for 'save to disk'  seen as 'opening file.pml' but functioning correctly

**Comment by sharonluk** [comment] 2016-03-13 18:24
I have tested all the features including authentication, 3rd party authentication , file upload etc. Everything is working well. Just having the same problem as Eamon.When I press save to disk ,it tells me I have chosen to open file.pml. However when I select the option to save or open file, the content of my pml code does actually exist.

**Comment by samcaulfield** [comment] 2016-03-13 18:32
That's a standard feature of Firefox and it's been doing that for as long as I can remember. It's nothing to worry about.

It wouldn't be a bad idea to mention that this dialog may appear in the README, for those who are new to Firefox.

**Comment by sharonluk** [comment] 2016-03-13 18:33
sure I can add that into README

**Comment by sharonluk** [comment] 2016-03-13 18:59
Just edited the README file with instructions for saving file to disk.

**Comment by gallagts** [comment] 2016-03-13 19:31
Just got back. Sorry for not oticing it earlier, I never thought to test it
myself before. Only today did I think to try and see if I could replicate
he problem Andrews had, and find a solution.

Turns out I replicated the problem eithout rrying. I am going into town
Tuesday to work on the magines in college. It will be easier than working
on the laptop emulator. I'll try and replixate it in college and find the
reason.

**Comment by Gulnur1** [comment] 2016-03-18 10:55
Will we close this issue as Andrew did not seem to have any problems the last time and Troy seem to have figured out why the issue occurred?

**Comment by samcaulfield** [comment] 2016-03-18 11:07
I think he said something about reinstalling the project while the project is open in the browser, then if you keep using the project without refreshing the page it breaks. @gallagts could you provide steps to reproduce the problem so we can understand what's happening and maybe put a warning in the README about it?

**Comment by sharonluk** [comment] 2016-03-18 16:58
Hey I'm testing the project here. And I think I have discovered what the bug with the signing in issue is. When I first register with a new email address and password, everything works fine. However when I reinstall the dependencies using "make install-deps" , try to sign in with the same email address and password, login fails and just freezes. However when i registered with a different email than previously, the sign in works then.

**Comment by sharonluk** [comment] 2016-03-19 13:19
After I reinstall the dependencies, It does not allow me sign to in with the previous email address. If i try to register with the same email address, it does not allow that either. This may mean the email address has to be different for every time the dependencies are reinstalled.

**Comment by samcaulfield** [comment] 2016-03-19 17:43
Thanks for the feedback Sharon but unfortunately I can't reproduce the behaviour you described. I'm not sure how reinstalling the dependencies would have an effect anyway since that script only modifies the repository directory and not the project directory on the server.

**Comment by samcaulfield** [comment] 2016-03-28 16:31
Troy can you still reproduce this?

**Comment by gallagts** [comment] 2016-03-28 16:32
Not since before no, I have been able to.

**Comment by samcaulfield** [comment] 2016-03-28 16:45
If your testing over the last 2 weeks hasn't found it I'm prepared to assume it's gone.

**Closed** 2016-03-28 16:44 UTC
Labels: bug
